name: Integración continua
on: push
env:
  URL_IMAGEN: ghcr.io/sergiovp/iv-organizeandgo:latest

jobs:
  main:
    name: Build and Push Docker Image to Github Container Registry and Run it
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push Exacution
        run: docker build -t $URL_IMAGEN . && docker push $URL_IMAGEN && docker run -t -v `pwd`:/test $URL_IMAGEN 