name: Integración continua
on: push
env:
  URL_IMAGEN: ghcr.io/sergiovp/iv-organizeandgo:latest

jobs:
  build-push-run-docker:
    name: Reconstruimos y atualizamos la imagen y ejecutamos los tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Comprobamos el repositorio para que podamos acceder a él
        uses: actions/checkout@v2
      -
        name: Nos logeamos en GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Ejecutamos los comandos para construir, actualizar y ejecutar los tests
        run: docker build -t $URL_IMAGEN . && docker push $URL_IMAGEN && docker run -t -v `pwd`:/test $URL_IMAGEN

