name: Publish Docker image
on: push
env:
  IMAGEN_URL: ghcr.io/sergiovp/iv-organizeandgo:latest

jobs:
  push_to_registry:
    name: Push Docker Image to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Github
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Action
        run: docker build -t $IMAGEN_URL . && docker push $IMAGEN_URL  